#ifndef __RTL8712_EEPROM_H
#define __RTL8712_EEPROM_H

#define	HWSET_MAX_SIZE_92S			256
#define EFUSE_MAX_SECTION			16
#define EFUSE_REAL_CONTENT_LEN			512
#define EFUSE_OOB_PROTECT_BYTES			15

#define RTL8190_EEPROM_ID			0x8129
#define EEPROM_HPON				0x02

#define EEPROM_VID				0x08
#define EEPROM_DID				0x0A

#define EEPROM_USB_OPTIONAL			0x0C // (&0x18)>>2 == #ep?
#define EEPROM_USB_PHY_PARA1			0x0D // 0x0D-0x11

#define EEPROM_MAC_ADDR				0x12
#define EEPROM_NODE_ADDRESS_BYTE_0		0x12

// 0x18-0x19?

#define EEPROM_VERSION				0x50
#define EEPROM_CHANNELPLAN			0x51
#define	EEPROM_CUSTOMID				0x52
#define EEPROM_SUBCUSTOMID			0x53
#define EEPROM_BOARDTYPE			0x54

#define EEPROM_TXPOWERBASE			0x55 // 0x55-0x66 // should be TxPwIndex
#define	EEPROM_TX_PWR_INDEX_RANGE		18
#define EEPROM_PWDIFF				0x67

#define EEPROM_THERMALMETER			0x68
#define EEPROM_CRYSTALCAP			0x69
//#define EEPROM_TXPOWERBASE			0x6A

#define EEPROM_TSSI_A				0x6B
#define EEPROM_TSSI_B				0x6C
//#define EEPROM_TXPWTKMODE			0x6D

#define EEPROM_TX_PWR_HT20_DIFF			0x6E // 0x6E-0x70
#define DEFAULT_HT20_TXPWR_DIFF			2
#define EEPROM_TX_PWR_OFDM_DIFF			0x71 // 0x71-0x72,0x82

// 0x73-0x78?

#define	EEPROM_TXPWRGROUP			0x79 // ???
#define EEPROM_REGULATORY			0x7A // ???

//#define TX_PWR_SAFETY_CHK			0x6D
//#define EEPROM_TXPWINDEX_CCK_24G		0x5D
//#define EEPROM_TXPWINDEX_OFDM_24G		0x6B
//#define EEPROM_HT2T_CH1_A			0x6c
//#define EEPROM_HT2T_CH7_A			0x6d
//#define EEPROM_HT2T_CH13_A			0x6e
//#define EEPROM_HT2T_CH1_B			0x6f
//#define EEPROM_HT2T_CH7_B			0x70
//#define EEPROM_HT2T_CH13_B			0x71

#define	EEPROM_RFIND_POWERDIFF			0x7B
#define	EEPROM_DEFAULT_LEGACYHTTXPOWERDIFF	0x3

//#define	EEPROM_BLUETOOTH_COEXIST		0x78
//#define	EEPROM_BLUETOOTH_TYPE			0x4f

//#define	EEPROM_OPTIONAL				0x78
//#define	EEPROM_WOWLAN				0x78

#define	EEPROM_CHANNEL_PLAN_FCC			0x0
#define	EEPROM_CHANNEL_PLAN_IC			0x1
#define	EEPROM_CHANNEL_PLAN_ETSI		0x2
#define	EEPROM_CHANNEL_PLAN_SPAIN		0x3
#define	EEPROM_CHANNEL_PLAN_FRANCE		0x4
#define	EEPROM_CHANNEL_PLAN_MKK			0x5
#define	EEPROM_CHANNEL_PLAN_MKK1		0x6
#define	EEPROM_CHANNEL_PLAN_ISRAEL		0x7
#define	EEPROM_CHANNEL_PLAN_TELEC		0x8
#define	EEPROM_CHANNEL_PLAN_GLOBAL_DOMAIN	0x9
#define	EEPROM_CHANNEL_PLAN_WORLD_WIDE_13	0xA
#define	EEPROM_CHANNEL_PLAN_NCC			0xB
#define	EEPROM_CHANNEL_PLAN_BY_HW_MASK		0x80

#endif /* __RTL8712_EEPROM_H */
