rtl8192s-common-objs :=		\
		main.o		\
		dm_common.o	\
		fw_common.o	\
		phy_common.o	\
		rf_common.o	\
		hw_common.o	\
		trx_common.o	\
		table_common.o	\
		led_common.o

obj-$(CONFIG_RTL8192S_COMMON) += rtl8192s-common.o

ccflags-y += -D__CHECK_ENDIAN__
